export interface CountryCode {
  code: string;
  flag: string;
  name: string;
  maxDigits: number;
}

export const countryCodes: CountryCode[] = [
  { code: "+351", flag: "🇵🇹", name: "Portugal",        maxDigits: 9  },
  { code: "+55",  flag: "🇧🇷", name: "Brazil",           maxDigits: 11 },
  { code: "+91",  flag: "🇮🇳", name: "India",            maxDigits: 10 },
  { code: "+244", flag: "🇦🇴", name: "Angola",           maxDigits: 9  },
  { code: "+238", flag: "🇨🇻", name: "Cape Verde",       maxDigits: 7  },
  { code: "+239", flag: "🇸🇹", name: "São Tomé",         maxDigits: 7  },
  { code: "+258", flag: "🇲🇿", name: "Mozambique",       maxDigits: 9  },
  { code: "+245", flag: "🇬🇼", name: "Guinea-Bissau",    maxDigits: 7  },
  { code: "+380", flag: "🇺🇦", name: "Ukraine",          maxDigits: 9  },
  { code: "+86",  flag: "🇨🇳", name: "China",            maxDigits: 11 },
  { code: "+977", flag: "🇳🇵", name: "Nepal",            maxDigits: 10 },
  { code: "+880", flag: "🇧🇩", name: "Bangladesh",       maxDigits: 10 },
  { code: "+234", flag: "🇳🇬", name: "Nigeria",          maxDigits: 10 },
  { code: "+92",  flag: "🇵🇰", name: "Pakistan",         maxDigits: 10 },
  { code: "+212", flag: "🇲🇦", name: "Morocco",          maxDigits: 9  },
  { code: "+7",   flag: "🇷🇺", name: "Russia",           maxDigits: 10 },
  { code: "+373", flag: "🇲🇩", name: "Moldova",          maxDigits: 8  },
  { code: "+40",  flag: "🇷🇴", name: "Romania",          maxDigits: 9  },
  { code: "+359", flag: "🇧🇬", name: "Bulgaria",         maxDigits: 9  },
  { code: "+34",  flag: "🇪🇸", name: "Spain",            maxDigits: 9  },
  { code: "+33",  flag: "🇫🇷", name: "France",           maxDigits: 9  },
  { code: "+44",  flag: "🇬🇧", name: "United Kingdom",   maxDigits: 10 },
  { code: "+49",  flag: "🇩🇪", name: "Germany",          maxDigits: 11 },
  { code: "+39",  flag: "🇮🇹", name: "Italy",            maxDigits: 10 },
  { code: "+31",  flag: "🇳🇱", name: "Netherlands",      maxDigits: 9  },
  { code: "+48",  flag: "🇵🇱", name: "Poland",           maxDigits: 9  },
  { code: "+90",  flag: "🇹🇷", name: "Turkey",           maxDigits: 10 },
  { code: "+57",  flag: "🇨🇴", name: "Colombia",         maxDigits: 10 },
  { code: "+58",  flag: "🇻🇪", name: "Venezuela",        maxDigits: 10 },
  { code: "+54",  flag: "🇦🇷", name: "Argentina",        maxDigits: 10 },
  { code: "+52",  flag: "🇲🇽", name: "Mexico",           maxDigits: 10 },
  { code: "+1",   flag: "🇺🇸", name: "USA / Canada",     maxDigits: 10 },
  { code: "+62",  flag: "🇮🇩", name: "Indonesia",        maxDigits: 11 },
  { code: "+63",  flag: "🇵🇭", name: "Philippines",      maxDigits: 10 },
  { code: "+94",  flag: "🇱🇰", name: "Sri Lanka",        maxDigits: 9  },
  { code: "+20",  flag: "🇪🇬", name: "Egypt",            maxDigits: 10 },
  { code: "+233", flag: "🇬🇭", name: "Ghana",            maxDigits: 9  },
  { code: "+254", flag: "🇰🇪", name: "Kenya",            maxDigits: 9  },
  { code: "+249", flag: "🇸🇩", name: "Sudan",            maxDigits: 9  },
  { code: "+251", flag: "🇪🇹", name: "Ethiopia",         maxDigits: 9  },
  { code: "+260", flag: "🇿🇲", name: "Zambia",           maxDigits: 9  },
  { code: "+263", flag: "🇿🇼", name: "Zimbabwe",         maxDigits: 9  },
  { code: "+66",  flag: "🇹🇭", name: "Thailand",         maxDigits: 9  },
  { code: "+84",  flag: "🇻🇳", name: "Vietnam",          maxDigits: 10 },
  { code: "+998", flag: "🇺🇿", name: "Uzbekistan",       maxDigits: 9  },
  { code: "+994", flag: "🇦🇿", name: "Azerbaijan",       maxDigits: 9  },
  { code: "+995", flag: "🇬🇪", name: "Georgia",          maxDigits: 9  },
  { code: "+374", flag: "🇦🇲", name: "Armenia",          maxDigits: 8  },
  { code: "+375", flag: "🇧🇾", name: "Belarus",          maxDigits: 9  },
  { code: "+7",   flag: "🇰🇿", name: "Kazakhstan",       maxDigits: 10 },
];
